# Étape 1 : Build de l'application React
FROM node:alpine AS build
WORKDIR '/app'
COPY package.json ./
RUN npm install
COPY . ./
RUN npm run build

# Étape 2 : Serveur Nginx pour héberger l'application
FROM nginx
COPY  --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]